/*Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 officeLamp.glb --transform 
Files: officeLamp.glb [3.66MB] > C:\Users\bogda\Desktop\Lamp\OtherLamp\officeLamp-transformed.glb [554.64KB] (85%)
Author: Kozlov Maksim (https://sketchfab.com/kozlovchik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-lamp-low-poly-0dded6b36c464294a0ab966b18109f6d
Title: Desk Lamp Low Poly
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function DeskLamp(props) {
  const { nodes, materials } = useGLTF("/officeLamp-transformed.glb");

  return (
    <group
      {...props}
      dispose={null}
      scale={0.315}
      position={[17.7, -3.6, 21]}
      rotation-y={Math.PI / -1.3}
    >
      <mesh
        geometry={nodes.Cylinder001_lamp_base_0.geometry}
        material={materials.lamp_base}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Helix007_lamp_0.geometry}
        material={materials.lamp}
        position={[0, 35.665, 11.453]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder070_base_0.geometry}
        material={materials.base}
        position={[-0.725, 5.463, -0.232]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line004_plastik_0.geometry}
        material={materials.plastik}
        position={[-0.724, 10.904, -3.898]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/officeLamp-transformed.glb");

export default DeskLamp;
