/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 a-maze-colour.glb --transform --shadows 
Files: a-maze-colour.glb [2.92MB] > C:\Users\bogda\Desktop\Maze\a-maze-colour-transformed.glb [130.98KB] (96%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Maps(props) {
  const { nodes, materials } = useGLTF("/a-maze-colour-transformed.glb");

  return (
    <RigidBody type="fixed" colliders="trimesh" position={[-0.2, -0.25, 9.15]}>
      {/* center position for testing purposes */}
      {/* <RigidBody type="fixed" colliders="trimesh" position={[-0.2, -0.25, -0.9]}> */}
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials["Material.006"]}
          scale={[10, 0.5, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials["Material.007"]}
          position={[0, -0.23, 0]}
          scale={[10, 1, 10]}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/a-maze-colour-transformed.glb");

export default Maps;
